name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./pay/pom.xml
          mvn clean package -f ./management/pom.xml
          mvn clean package -f ./enrollment/pom.xml
          mvn clean package -f ./notification/pom.xml
          mvn clean package -f ./customercenter/pom.xml

      - name: Docker Build and push for Pay
        uses: docker/build-push-action@v4
        with:
          context: ./pay
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/pay:latest
            ghcr.io/${{ github.repository }}/pay:${{ github.ref_name }}
            
      - name: Docker Build and push for Management
        uses: docker/build-push-action@v4
        with:
          context: ./management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/management:latest
            ghcr.io/${{ github.repository }}/management:${{ github.ref_name }}
            
      - name: Docker Build and push for Enrollment
        uses: docker/build-push-action@v4
        with:
          context: ./enrollment
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/enrollment:latest
            ghcr.io/${{ github.repository }}/enrollment:${{ github.ref_name }}
            
      - name: Docker Build and push for Notification
        uses: docker/build-push-action@v4
        with:
          context: ./notification
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/notification:latest
            ghcr.io/${{ github.repository }}/notification:${{ github.ref_name }}
            
      - name: Docker Build and push for Customercenter
        uses: docker/build-push-action@v4
        with:
          context: ./customercenter
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/customercenter:latest
            ghcr.io/${{ github.repository }}/customercenter:${{ github.ref_name }}
            
